# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 801)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(170, 170, 255);\n"
"")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-30, 0, 251, 801))
        self.widget.setStyleSheet("background-color: rgb(117, 117, 175);\n"
"border-radius: 32px;")
        self.widget.setObjectName("widget")
        self.hair = QtWidgets.QPushButton(self.widget)
        self.hair.setGeometry(QtCore.QRect(50, 160, 61, 60))
        self.hair.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;\n"
"\n"
"")
        self.hair.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/face_3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hair.setIcon(icon)
        self.hair.setIconSize(QtCore.QSize(32, 32))
        self.hair.setObjectName("hair")
        self.spa = QtWidgets.QPushButton(self.widget)
        self.spa.setGeometry(QtCore.QRect(50, 240, 60, 60))
        self.spa.setAutoFillBackground(False)
        self.spa.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;\n"
"\n"
"")
        self.spa.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/spa_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.spa.setIcon(icon1)
        self.spa.setIconSize(QtCore.QSize(32, 32))
        self.spa.setObjectName("spa")
        self.text = QtWidgets.QLabel(self.widget)
        self.text.setGeometry(QtCore.QRect(70, 50, 121, 51))
        self.text.setStyleSheet("font: italic 16pt \"Sitka Small\";")
        self.text.setObjectName("text")
        self.nails = QtWidgets.QPushButton(self.widget)
        self.nails.setGeometry(QtCore.QRect(50, 320, 60, 60))
        self.nails.setAutoFillBackground(False)
        self.nails.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;\n"
"\n"
"")
        self.nails.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/pan_tool_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nails.setIcon(icon2)
        self.nails.setIconSize(QtCore.QSize(32, 32))
        self.nails.setObjectName("nails")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 180, 101, 21))
        self.label.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(120, 260, 101, 21))
        self.label_2.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(120, 340, 71, 21))
        self.label_3.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 680, 60, 60))
        self.pushButton_4.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/close_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(52, 52))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(120, 695, 71, 31))
        self.label_4.setStyleSheet("font: 13pt \"Mongolian Baiti\";")
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(280, 280, 701, 451))
        self.tableWidget.setStyleSheet("background-color: rgb(103, 114, 127);\n"
"border-radius: 13px;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.del_qwe = QtWidgets.QPushButton(self.centralwidget)
        self.del_qwe.setGeometry(QtCore.QRect(864, 192, 101, 51))
        self.del_qwe.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 13px;")
        self.del_qwe.setObjectName("del_qwe")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 189, 141, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(103, 114, 127);\n"
"border-radius: 13px;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(864, 130, 101, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 13px;")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "SabrinaSPA"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "HAIR"))
        self.label_2.setText(_translate("MainWindow", "SPA"))
        self.label_3.setText(_translate("MainWindow", "NAILS"))
        self.label_4.setText(_translate("MainWindow", "DB"))
        self.del_qwe.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_2.setText(_translate("MainWindow", "Обновить"))
import res_rc
