# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hair.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 798)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(170, 170, 255);\n"
"")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-30, 0, 251, 801))
        self.widget.setStyleSheet("background-color: rgb(117, 117, 175);\n"
"border-radius: 32px;")
        self.widget.setObjectName("widget")
        self.hair = QtWidgets.QPushButton(self.widget)
        self.hair.setGeometry(QtCore.QRect(50, 160, 61, 60))
        self.hair.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;\n"
"\n"
"")
        self.hair.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/face_3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hair.setIcon(icon)
        self.hair.setIconSize(QtCore.QSize(32, 32))
        self.hair.setObjectName("hair")
        self.spa = QtWidgets.QPushButton(self.widget)
        self.spa.setGeometry(QtCore.QRect(50, 240, 60, 60))
        self.spa.setAutoFillBackground(False)
        self.spa.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;\n"
"\n"
"")
        self.spa.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/spa_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.spa.setIcon(icon1)
        self.spa.setIconSize(QtCore.QSize(32, 32))
        self.spa.setObjectName("spa")
        self.text = QtWidgets.QLabel(self.widget)
        self.text.setGeometry(QtCore.QRect(70, 50, 121, 51))
        self.text.setStyleSheet("font: italic 16pt \"Sitka Small\";")
        self.text.setObjectName("text")
        self.nails = QtWidgets.QPushButton(self.widget)
        self.nails.setGeometry(QtCore.QRect(50, 320, 60, 60))
        self.nails.setAutoFillBackground(False)
        self.nails.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;\n"
"\n"
"")
        self.nails.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/pan_tool_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nails.setIcon(icon2)
        self.nails.setIconSize(QtCore.QSize(32, 32))
        self.nails.setObjectName("nails")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 180, 101, 21))
        self.label.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(120, 260, 101, 21))
        self.label_2.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(120, 340, 71, 21))
        self.label_3.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 680, 60, 60))
        self.pushButton_4.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/close_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(52, 52))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(120, 695, 71, 31))
        self.label_4.setStyleSheet("font: 13pt \"Mongolian Baiti\";")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(270, 100, 731, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(260, 108, 20, 611))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(270, 710, 731, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1000, 108, 3, 611))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 130, 111, 111))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 52px;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/girls1(1)-round.png"))
        self.label_5.setObjectName("label_5")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(270, 270, 731, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(270, 430, 731, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(270, 570, 731, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 170, 251, 31))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 12pt \"Sitka Display\";\n"
"border-radius: 4px;")
        self.label_6.setObjectName("label_6")
        self.vika_combo = QtWidgets.QComboBox(self.centralwidget)
        self.vika_combo.setGeometry(QtCore.QRect(680, 170, 131, 31))
        self.vika_combo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"font: italic 12pt \"Sitka Display\";")
        self.vika_combo.setObjectName("vika_combo")
        self.vika_combo.addItem("")
        self.vika_combo.addItem("")
        self.vika_combo.addItem("")
        self.vika_combo.addItem("")
        self.vika_combo.addItem("")
        self.vika_combo.addItem("")
        self.vika_combo.addItem("")
        self.zapis_vika = QtWidgets.QPushButton(self.centralwidget)
        self.zapis_vika.setGeometry(QtCore.QRect(840, 170, 111, 31))
        self.zapis_vika.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 4px;\n"
"font: italic 12pt \"Sitka Display\";\n"
"")
        self.zapis_vika.setObjectName("zapis_vika")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "SabrinaSPA"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "HAIR"))
        self.label_2.setText(_translate("MainWindow", "SPA"))
        self.label_3.setText(_translate("MainWindow", "NAILS"))
        self.label_4.setText(_translate("MainWindow", "DB"))
        self.label_6.setText(_translate("MainWindow", "Вика, стаж работы 2 года, 37 лет"))
        self.vika_combo.setItemText(0, _translate("MainWindow", "9:00"))
        self.vika_combo.setItemText(1, _translate("MainWindow", "11:00"))
        self.vika_combo.setItemText(2, _translate("MainWindow", "13:00"))
        self.vika_combo.setItemText(3, _translate("MainWindow", "15:00"))
        self.vika_combo.setItemText(4, _translate("MainWindow", "17:00"))
        self.vika_combo.setItemText(5, _translate("MainWindow", "19:00"))
        self.vika_combo.setItemText(6, _translate("MainWindow", "21:00"))
        self.zapis_vika.setText(_translate("MainWindow", "Записаться"))
import res_rc
